trigger: none
resources:
  pipelines:
  - pipeline: Pipeline1
    source: Pipeline1
    trigger:
      enabled: true
stages:
- stage: stage1
  jobs:
  - job: download_specific_artifact
    displayName: download specific artifact
    steps:
      - download: Pipeline1
        artifact: artifact1
  
- template: tenant-deployment-template.yml
  parameters:
    tenant: SomeTenant