parameters:
- name: tenant
  type: string
  default: ''
- name: environment
  type: string
  default: ''
- name: dependsOnEnvironment
  type: string
  default: ''
- name: namespace
  type: string
  default: ''
- name: dbServer
  type: string
  default: 'k8s-int-db.ignite.systems'
- name: database
  type: string
  default: ''

stages:
- stage: ${{parameters.tenant}}_${{parameters.environment}}
  displayName: ${{parameters.tenant}} ${{parameters.environment}}
  ${{ if eq(parameters.dependsOnEnvironment, '') }}:
    dependsOn: []
  ${{ if not(eq(parameters.dependsOnEnvironment, '')) }}:
    dependsOn: ${{parameters.tenant}}_${{parameters.dependsOnEnvironment}}
  jobs:
    - deployment: deploy
      variables:
        k8sNamespace: ${{parameters.tenant}}
      displayName: Deploy helm chart into AKS
      pool:
        name: linux
      environment: ${{parameters.environment}}.${{parameters.namespace}}
      strategy:
        runOnce:
          deploy:
            steps:
              - checkout: none
